
resources:
  pipelines:
  - pipeline: nugetclientofficial
    source: NuGet.Client-Official
    trigger:
        branches:
          - dev

jobs:
  - job:
    displayName: Get URL

    steps:
      - task: DownloadPipelineArtifact@2
        displayName: "Download symbols - NonRTM artifact"
        inputs:
          source: specific
          project: "devdiv"
          pipeline: "NuGet.Client-Official"
          artifact: "symbols - NonRTM"
          path: $(Pipeline.Workspace)\symbols\NonRTM
  - job: 
    displayName: Bash URL
    steps:
      - bash: echo "$(Build.Repository.LocalPath)"
      - bash: echo "$(resources.pipeline)"