
resources:
  pipelines:
  - pipeline: nugetclientofficial
    source: NuGet.Client-Official
    trigger:
        branches:
          - dev

stages:
- stage: GetUrl
  displayName: Get URL
  dependsOn: []
  jobs:
    - job:

      steps:
        - task: DownloadPipelineArtifact@2
          displayName: "Download symbols - NonRTM artifact"
          inputs:
            source: specific
            project: "devdiv"
            pipeline: "NuGet.Client-Official"
            artifact: "symbols - NonRTM"
            path: $(Pipeline.Workspace)\symbols\NonRTM

- stage: BashURL
  displayName: Bash URL
  dependsOn: GetUrl
  jobs:
  - job: 
    steps:
      - bash: echo "$(Build.Repository.LocalPath)"
      - bash: echo "$(resources.pipeline)"