parameters:
- name: DartLabEnvironment
  displayName: DartLab Environment
  type: string
  default: Production
  values:
  - Production
  - Staging
  
resources:
  pipelines:
  - pipeline: DartLab
    source: DartLab
    branch: main
  - pipeline: NuGet
    source: NuGet.Client-PrivateDev
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/main

stages:
- template: templates/End_To_End_Tests_On_Windows.yml
  parameters:
    stageName: VS_EndToEnd_Part1
    stageDisplayName: VS EndToEnd Tests Part 1
    condition: "and(succeeded(), eq(variables['RunEndToEndTests'], 'true'))"
    testExecutionJobTimeoutInMinutes: 100
    bootstrapperUrl: $(VsBootstrapperUrl)
    runSettingsURI:  https://vsdrop.corp.microsoft.com/file/v1/RunSettings/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildId);NuGet.Tests.Apex.runsettings
    DartLabEnvironment: ${{parameters.DartLabEnvironment}}
    variables:
    - name: VsBootstrapperUrl
      value: $[stageDependencies.Build_Insertable.Build_and_UnitTest_NonRTM.outputs['vsbootstrapper.bootstrapperUrl']]
    - name: GitHubStatusName
      value: End_To_End_Tests_On_Windows Part1
    part: "InstallPackageTest.ps1,UninstallPackageTest.ps1,UpdatePackageTest.ps1"